In [9]:
import pandas as pd

In [10]:
file = pd.read_csv("global-data-on-sustainable-energy.csv")

In [11]:
file

,Entity,Year,Access to electricity (% of population),Access to clean fuels for cooking,Renewable-electricity-generating-capacity-per-capita,Financial flows to developing countries (US $),Renewable energy share in the total final energy consumption (%),Electricity from fossil fuels (TWh),Electricity from nuclear (TWh),Electricity from renewables (TWh),...,Primary energy consumption per capita (kWh/person),Energy intensity level of primary energy (MJ/$2017 PPP GDP),Value_co2_emissions_kt_by_country,Renewables (% equivalent primary energy),gdp_growth,gdp_per_capita,Density\n(P/Km2),Land Area(Km2),Latitude,Longitude
0,Afghanistan,2000,1.613591,6.2,9.22,20000.0,44.99,0.16,0.0,0.31,...,302.59482,1.64,760.000000,NaN,NaN,NaN,60,652230.0,33.939110,67.709953
1,Afghanistan,2001,4.074574,7.2,8.86,130000.0,45.60,0.09,0.0,0.50,...,236.89185,1.74,730.000000,NaN,NaN,NaN,60,652230.0,33.939110,67.709953
2,Afghanistan,2002,9.409158,8.2,8.47,3950000.0,37.83,0.13,0.0,0.56,...,210.86215,1.40,1029.999971,NaN,NaN,179.426579,60,652230.0,33.939110,67.709953
3,Afghanistan,2003,14.738506,9.5,8.09,25970000.0,36.66,0.31,0.0,0.63,...,229.96822,1.40,1220.000029,NaN,8.832278,190.683814,60,652230.0,33.939110,67.709953
4,Afghanistan,2004,20.064968,10.9,7.75,NaN,44.24,0.33,0.0,0.56,...,204.23125,1.20,1029.999971,NaN,1.414118,211.382074,60,652230.0,33.939110,67.709953
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3644,Zimbabwe,2016,42.561730,29.8,62.88,30000.0,81.90,3.50,0.0,3.32,...,3227.68020,10.00,11020.000460,NaN,0.755869,1464.588957,38,390757.0,-19.015438,29.154857
3645,Zimbabwe,2017,44.178635,29.8,62.33,5570000.0,82.46,3.05,0.0,4.30,...,3068.01150,9.51,10340.000150,NaN,4.709492,1235.189032,38,390757.0,-19.015438,29.154857
3646,Zimbabwe,2018,45.572647,29.9,82.53,10000.0,80.23,3.73,0.0,5.46,...,3441.98580,9.83,12380.000110,NaN,4.824211,1254.642265,38,390757.0,-19.015438,29.154857
3647,Zimbabwe,2019,46.781475,30.1,81.40,250000.0,81.50,3.66,0.0,4.58,...,3003.65530,10.47,11760.000230,NaN,-6.144236,1316.740657,38,390757.0,-19.015438,29.154857
3648,Zimbabwe,2020,52.747670,30.4,80.61,30000.0,81.90,3.40,0.0,4.19,...,2680.13180,10.00,NaN,NaN,-6.248748,1214.509820,38,390757.0,-19.015438,29.154857

In [12]:
df = pd.DataFrame(file)

In [18]:
df.query("Year == 2020")

,Entity,Year,Access to electricity (% of population),Access to clean fuels for cooking,Renewable-electricity-generating-capacity-per-capita,Financial flows to developing countries (US $),Renewable energy share in the total final energy consumption (%),Electricity from fossil fuels (TWh),Electricity from nuclear (TWh),Electricity from renewables (TWh),...,Primary energy consumption per capita (kWh/person),Energy intensity level of primary energy (MJ/$2017 PPP GDP),Value_co2_emissions_kt_by_country,Renewables (% equivalent primary energy),gdp_growth,gdp_per_capita,Density\n(P/Km2),Land Area(Km2),Latitude,Longitude
20,Afghanistan,2020,97.700000,33.20,9.35,NaN,NaN,0.12,0.0,0.68,...,702.8880,NaN,NaN,NaN,-2.351101,516.747871,60,652230.0,33.939110,67.709953
41,Albania,2020,100.000000,81.30,NaN,NaN,NaN,0.00,0.0,5.31,...,11158.0030,NaN,NaN,NaN,-3.955398,5246.292306,105,28748.0,41.153332,20.168331
62,Algeria,2020,99.804130,99.70,15.64,NaN,NaN,72.01,0.0,0.72,...,14933.8070,NaN,NaN,0.297899,-5.100000,3306.858208,18,2381741.0,28.033886,1.659626
83,Angola,2020,46.890610,50.20,115.43,NaN,NaN,4.49,0.0,12.10,...,3527.1600,NaN,NaN,NaN,-5.399987,1776.166868,26,1246700.0,-11.202692,17.873887
104,Antigua and Barbuda,2020,100.000000,100.00,167.98,NaN,NaN,0.31,0.0,0.02,...,27785.2270,NaN,NaN,NaN,-20.192371,13992.744480,223,443.0,17.060816,-61.796428
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3564,Uzbekistan,2020,100.000000,84.25,60.02,NaN,NaN,50.93,0.0,5.01,...,15860.6090,NaN,NaN,2.523421,1.714771,1750.697113,79,447400.0,41.377491,64.585262
3585,Vanuatu,2020,67.333270,7.60,37.84,NaN,NaN,0.05,0.0,0.02,...,2923.5380,NaN,NaN,NaN,-6.813991,2870.089300,25,12189.0,-15.376706,166.959158
3606,Yemen,2020,73.757930,61.50,8.48,NaN,NaN,2.74,0.0,0.49,...,1092.0021,NaN,NaN,NaN,NaN,NaN,56,527968.0,15.552727,48.516388
3627,Zambia,2020,44.524475,10.40,138.23,NaN,NaN,2.00,0.0,13.10,...,3099.0830,NaN,NaN,NaN,-2.785055,985.132436,25,752618.0,-13.133897,27.849332
3648,Zimbabwe,2020,52.747670,30.40,80.61,30000.0,81.9,3.40,0.0,4.19,...,2680.1318,10.0,NaN,NaN,-6.248748,1214.509820,38,390757.0,-19.015438,29.154857

In [19]:
df2 = df.query("Year == 2020")

In [23]:
df2.to_csv("2020_data.csv", index=False)